#pragma once

#define MAIN_Version "dba66c7"
#define KNX_Version "2.2.2+f6111d3"
#define MODULE_BusPowerSupply_Version "0.1.0+c447d9c"
#define MODULE_BusPowerSupply_Version_Major 0
#define MODULE_BusPowerSupply_Version_Minor 1
#define MODULE_BusPowerSupply_Version_Revision 0
#define MODULE_BusPowerSupply_ETS 1
#define MODULE_Common_Version "1.7.2+3ce0b9e"
#define MODULE_Common_Version_Major 1
#define MODULE_Common_Version_Minor 7
#define MODULE_Common_Version_Revision 2
#define MODULE_Common_ETS 23
#define MODULE_LogicModule_Version "4.0.1+2bc2557"
#define MODULE_LogicModule_Version_Major 4
#define MODULE_LogicModule_Version_Minor 0
#define MODULE_LogicModule_Version_Revision 1
#define MODULE_LogicModule_ETS 64
#define MODULE_FileTransferModule_Version "0.1.5+178f186"
#define MODULE_FileTransferModule_Version_Major 0
#define MODULE_FileTransferModule_Version_Minor 1
#define MODULE_FileTransferModule_Version_Revision 5
#define MODULE_FileTransferModule_ETS 1
#define MODULE_FunctionBlocks_Version "0.9.1+d7f5bdd"
#define MODULE_FunctionBlocks_Version_Major 0
#define MODULE_FunctionBlocks_Version_Minor 9
#define MODULE_FunctionBlocks_Version_Revision 1
#define MODULE_FunctionBlocks_ETS 9
